// Die Texte des Panels auf Deutsch und Englisch. Spec C8 Abschnitt 9.
//
// Deutsch, wenn Home Assistant Deutsch spricht, sonst Englisch, wie in C3.
// Die Meldungen mit den Schluesseln aus C3-Spec 2.3 stehen hier wortgleich
// wie in translations/de.json und en.json; tests/panel/texte.test.mjs prueft das.

export const TEXTE = {
  de: {
    // C3-Spec 2.3, wortgleich mit translations/de.json
    zeit_fehlt: 'Abfahrt und Rückkehr brauchen Datum und Uhrzeit.',
    rueckkehr_vor_abfahrt: 'Die Rückkehr muss nach der Abfahrt liegen.',
    rueckkehr_vorbei: 'Die Rückkehr liegt in der Vergangenheit.',
    dauer_zu_lang: 'Der Termin dauert länger, als bis er sich wiederholt.',
    strecke_fehlt: 'Strecke fehlt.',
    strecke_negativ: 'Die Strecke kann nicht negativ sein.',
    ladestand_bereich: 'Der Ladestand liegt zwischen 0 und 100 %.',
    ladestand_unter_min: 'Liegt unter dem Min-SoC von {min} % und wird ignoriert.',
    fahrt_zu_weit: 'Auch voll geladen reicht es nicht für {km} km — unterwegs laden.',
    fahrt_unter_min: 'Die Fahrt zieht den Ladestand unter den Min-SoC von {min} %.',
    ladestand_offen: 'Ohne Haken und ohne Ziel ist der Ladestand bei der Abfahrt nicht zugesagt.',
    rueckkehr_mit: 'Rückkehr mitverschoben, die Dauer bleibt.',
    fahrer_doppelt: '{fahrer} ist {datum} zur selben Zeit mit {fahrzeug} unterwegs.',
    fahrzeug_unbekannt: 'Das ist kein Fahrzeug von Meteo-Volt.',
    eintrag_unbekannt: 'Diesen Termin gibt es nicht mehr.',
    termin_unbekannt: 'An diesem Datum gibt es den Termin nicht.',
    umfang_unzulaessig: 'Eine geänderte Wiederholung gilt nicht nur für diesen Termin.',
    rueckgaengig_unmoeglich: 'Das lässt sich nicht mehr rückgängig machen.',
    plan_pause: 'Neu planen geht erst in {sekunden} s wieder.',
    plan_gestoppt: 'Der API-Key wurde abgelehnt. Neu planen geht erst nach einem neuen Key oder einem Neustart.',

    // Werkzeugleiste, Tabs, Zustaende
    titel: 'Meteo-Volt',
    seitenleiste: 'Seitenleiste',
    tab_uebersicht: 'Übersicht',
    tab_preise: 'Preise',
    tabs: 'Bereiche',
    neu_planen: 'Neu planen',
    plan_von: 'Plan von {zeit}',
    plan_laeuft: 'Plan wird berechnet …',
    kein_plan: 'Noch kein Plan',
    plan_gescheitert: 'Der letzte Versuch zu planen ist gescheitert: {fehler}',
    laedt: 'Lädt …',
    nicht_geladen: 'Meteo-Volt ist nicht geladen.',
    termin_knopf: 'Termin',
    rueckgaengig: 'Rückgängig',
    schliessen: 'Schließen',
    abbrechen: 'Abbrechen',
    speichern: 'Speichern',
    loeschen: 'Löschen',
    ok: 'OK',
    mehr_termine: 'Weitere Termine anzeigen',

    // Zeitraum und Netzentgelt
    zeitraum: 'Zeitraum',
    h48: '48 h',
    bis_tag: 'Bis {tag}',
    preisart: 'Preis',
    boerse: 'Börse',
    mit_netzentgelt: 'Mit Netzentgelt',
    hinweis_mit_netzentgelt: 'Mit Netzentgelt {ct}',
    hinweis_nur_boerse: 'Nur Börsenpreis',
    hinweis_kein_netzentgelt: 'Börsenpreis, kein Netzentgelt angegeben',

    // Uebersicht
    risiko: 'Risiko',
    risiko_1: 'Sparsam',
    risiko_2: 'Ausgewogen',
    risiko_3: 'Sicher',
    risiko_satz_1: 'Wartet auf günstige Preise und nimmt dafür mehr Risiko in Kauf.',
    risiko_satz_2: 'Plant mit dem mittleren Preis der Prognose.',
    risiko_satz_3: 'Lädt früher und sichert gegen steigende Preise ab.',
    risiko_alle: 'Gilt für alle Fahrzeuge.',
    ladeplan_bis: 'Ladeplan bis {tag} {zeit}',
    ladeplan: 'Ladeplan',
    strompreis: 'Strompreis',
    termine_aller: 'Termine aller Fahrzeuge',
    filter_fahrer: 'Nach Fahrer filtern',
    filter_alle: 'Alle',
    filter_ohne: 'Ohne Fahrer',
    keine_termine_tage: 'Keine Termine in den nächsten Tagen.',

    // Legende und Diagramme
    leg_ladestand: 'Ladestand',
    leg_laden: 'Laden',
    leg_unterwegs: 'Unterwegs',
    leg_preis: 'Preis',
    leg_prognose: 'Prognose',
    diagramm_min: 'Min {soc}',
    diagramm_max: 'Max {soc}',
    diagramm_ziel: 'Ziel {soc}',
    diagramm_plan: 'Ladeplan {name}: Ladestand, Laden und Preis über den Horizont',
    tip_ladestand: 'Ladestand {soc}',
    tip_preis: 'Preis {preis}',
    tip_preis_prognose: 'Preis {preis} (Prognose)',
    tip_laedt: 'Lädt {kw}, {eur}',
    tip_unterwegs: 'Unterwegs',

    // Status eines Fahrzeugs
    st_unterwegs_bis: 'Unterwegs bis {zeit}',
    st_laedt_jetzt: 'Lädt jetzt, {kw}',
    st_laedt_jetzt_ohne: 'Lädt jetzt',
    st_laedt_ab: 'Lädt ab {zeit}',
    st_kein_laden: 'Kein Laden geplant',
    st_warnung_1: '1 Termin mit Warnung',
    st_warnung_n: '{n} Termine mit Warnung',
    morgen_zeit: 'morgen {zeit}',

    // Plankarte
    kz_ladestand: 'Ladestand jetzt',
    kz_geplant: 'Geplant',
    kz_kosten_mit: 'Kosten mit Netzentgelt',
    kz_kosten_ohne: 'Kosten ohne Netzentgelt',
    kz_planende: 'Am Planende',
    ladebloecke: 'Ladeblöcke',
    kein_laden_bis_ende: 'Bis zum Planende ist kein Laden geplant.',
    alle_bloecke: 'Alle {n} Ladeblöcke anzeigen',
    weniger: 'Weniger anzeigen',
    grund_ziel: 'für Abfahrt {abfahrt}, Ziel {soc}',
    grund_vor: 'vor Abfahrt {abfahrt}',
    grund_ende: 'bis zum Planende',
    block_werte: '{kwh} · Ø {preis} · {eur} · {grund}',

    // Termine
    einzeln_geaendert: 'einzeln geändert',
    ziel_soc: 'Ziel {soc}',
    abfahrt_mit: 'Abfahrt mit {soc}',
    ziel_unerreichbar: 'Ziel {soc} nicht erreichbar, es fehlen {kwh}',
    unter_min: 'Nach der Fahrt {soc}, unter dem Min-SoC von {min}',
    hinweis_overlap: 'Überschneidet sich mit einem anderen Termin dieses Autos',
    hinweis_fahrer: '{fahrer} ist zur selben Zeit mit {fahrzeug} unterwegs',
    anderes_fahrzeug: 'einem anderen Fahrzeug',
    noch_nicht_geplant: 'Ab {tag} {zeit} noch nicht geplant',
    keine_termine: 'Keine Termine. Ohne Termine plant Meteo-Volt ohne Fahrten.',
    kopf_heute: 'Heute, {tag}',
    kopf_morgen: 'Morgen, {tag}',
    km: '{km} km',

    // Wiederholung
    regel_once: 'Einmalig',
    regel_daily: 'Täglich',
    regel_weekdays: 'Jeden Werktag (Mo–Fr)',
    regel_weekdays_kurz: 'Mo–Fr',
    regel_weekly: 'Wöchentlich am {wochentag}',
    regel_weekly_kurz: 'Jeden {wochentag}',
    regel_monthly: 'Monatlich am {ordinal} {wochentag}',
    regel_monthly_kurz: 'Monatlich',
    regel_yearly: 'Jährlich am {datum}',

    // Formular
    neuer_termin: 'Neuer Termin',
    termin_bearbeiten: 'Termin bearbeiten',
    f_abfahrt: 'Abfahrt',
    f_rueckkehr: 'Rückkehr',
    f_wiederholung: 'Wiederholung',
    f_strecke: 'Strecke hin und zurück (km)',
    f_fahrzeug: 'Fahrzeug',
    f_fahrer: 'Fahrer',
    f_kein_fahrer: 'Kein Fahrer',
    f_ladestand: 'Ladestand bei Abfahrt (%)',
    f_sichern: 'Min-SoC sichern',
    f_sichern_hinweis: 'Sichert {ziel} % — Min-SoC {min} % plus {fahrt} % für {km} km',
    f_optional: 'optional',

    // Umfang
    umfang_aendern: 'Wiederkehrenden Termin ändern',
    umfang_loeschen: 'Wiederkehrenden Termin löschen',
    umfang_this: 'Nur dieser Termin',
    umfang_following: 'Dieser und alle folgenden',
    umfang_all: 'Alle Termine',
    umfang_gesperrt: 'Geht nicht, wenn sich die Wiederholung ändert.',
    umfang_zuruecksetzen: 'Einzeln geänderte und abgesagte Termine dieser Serie werden zurückgesetzt.',

    // Ueberschneidung
    ue_titel_1: 'Überschneidet sich mit einem Termin',
    ue_titel_n: 'Überschneidet sich mit {n} Terminen',
    ue_frage: '{fahrzeug} ist in dieser Zeit schon eingeplant. Welche Termine sollen entfallen?',
    ue_behalten: 'Behalten',
    ue_absagen_1: '1 Termin absagen',
    ue_absagen_n: '{n} Termine absagen',
    ue_einmalig: 'Einmalig',

    // Meldungen unten
    m_gespeichert: 'Termin gespeichert. Plan wird neu berechnet.',
    m_geloescht: 'Termin gelöscht.',
    m_abgesagt: 'Termin abgesagt.',
    m_geloescht_n: 'Termine gelöscht.',
    m_gespeichert_abgesagt_1: 'Termin gespeichert, 1 Termin abgesagt.',
    m_gespeichert_abgesagt_n: 'Termin gespeichert, {n} Termine abgesagt.',

    // Tab Preise
    p_jetzt: 'Preis jetzt',
    p_jetzt_mit: 'Preis jetzt, mit Netzentgelt',
    p_heute: 'Günstigste {h} h heute, Ø {preis}',
    p_morgen: 'Günstigste {h} h morgen, Ø {preis}',
    p_letzter_tag: 'Letzter Tag mit Börsenpreisen',
    p_leg_boerse: 'Börse',
    p_leg_prognose: 'Prognose Q50',
    p_leg_spanne: 'Spanne Q10 bis Q90',
    p_leg_guenstig: 'Günstigste {h} h je Tag',
    p_prognose_von: 'Prognose von {zeit}, Modell {modell}.',
    p_je_tag: 'Je Tag',
    p_laenge: 'Länge des günstigsten Zeitraums',
    p_kopf_tag: 'Tag',
    p_kopf_guenstig: 'Günstigste {h} h',
    p_kopf_werte: 'Tief, Hoch, Mittel',
    p_quelle_boerse: 'Börse',
    p_quelle_prognose: 'Prognose',
    p_ab: 'ab {zeit}',
    p_bis: 'bis {zeit}',
    p_zu_kurz: 'zu kurz',
    p_werte: 'Tief {tief} um {tiefzeit} · Hoch {hoch} um {hochzeit} · Ø {mittel}',
    p_spanne: 'Spanne ± {spanne}',
    p_keine: 'Noch keine Prognose.',
    p_tip_boerse: 'Börsenpreis {preis}',
    p_tip_prognose: 'Prognose {preis}',
    p_tip_spanne: 'Spanne {von} bis {bis}',
    p_diagramm: 'Preisprognose mit Spanne',
    ohne_wert: '–',
    durchschnitt: 'Ø {preis}',
    eur_betrag: '{betrag} €',
    von_bis: '{von}–{bis}',
    soc_von_bis: '{von} → {bis}',
    trenner: ' · ',
  },
  en: {
    // C3-Spec 2.3, word for word as in translations/en.json
    zeit_fehlt: 'Departure and return need a date and a time.',
    rueckkehr_vor_abfahrt: 'The return must be after the departure.',
    rueckkehr_vorbei: 'The return is in the past.',
    dauer_zu_lang: 'The trip lasts longer than the time until it repeats.',
    strecke_fehlt: 'Distance missing.',
    strecke_negativ: 'The distance cannot be negative.',
    ladestand_bereich: 'The state of charge is between 0 and 100 %.',
    ladestand_unter_min: 'Below the minimum state of charge of {min} % and ignored.',
    fahrt_zu_weit: 'Even fully charged it is not enough for {km} km — charge on the way.',
    fahrt_unter_min: 'The trip pulls the state of charge below the minimum of {min} %.',
    ladestand_offen: 'Without the tick and without a target the state of charge at departure is not promised.',
    rueckkehr_mit: 'Return moved along, the duration stays.',
    fahrer_doppelt: '{fahrer} is on the road with {fahrzeug} at the same time on {datum}.',
    fahrzeug_unbekannt: 'This is not a Meteo-Volt vehicle.',
    eintrag_unbekannt: 'This trip no longer exists.',
    termin_unbekannt: 'There is no such trip on this date.',
    umfang_unzulaessig: 'A changed repeat cannot apply to this trip only.',
    rueckgaengig_unmoeglich: 'This can no longer be undone.',
    plan_pause: 'Replanning is possible again in {sekunden} s.',
    plan_gestoppt: 'The API key was rejected. Replanning works again after a new key or a restart.',

    titel: 'Meteo-Volt',
    seitenleiste: 'Sidebar',
    tab_uebersicht: 'Overview',
    tab_preise: 'Prices',
    tabs: 'Sections',
    neu_planen: 'Replan',
    plan_von: 'Plan from {zeit}',
    plan_laeuft: 'Planning …',
    kein_plan: 'No plan yet',
    plan_gescheitert: 'The last planning attempt failed: {fehler}',
    laedt: 'Loading …',
    nicht_geladen: 'Meteo-Volt is not loaded.',
    termin_knopf: 'Trip',
    rueckgaengig: 'Undo',
    schliessen: 'Close',
    abbrechen: 'Cancel',
    speichern: 'Save',
    loeschen: 'Delete',
    ok: 'OK',
    mehr_termine: 'Show more trips',

    zeitraum: 'Range',
    h48: '48 h',
    bis_tag: 'Until {tag}',
    preisart: 'Price',
    boerse: 'Exchange',
    mit_netzentgelt: 'With grid fees',
    hinweis_mit_netzentgelt: 'With grid fees {ct}',
    hinweis_nur_boerse: 'Exchange price only',
    hinweis_kein_netzentgelt: 'Exchange price, no grid fees set',

    risiko: 'Risk',
    risiko_1: 'Economical',
    risiko_2: 'Balanced',
    risiko_3: 'Safe',
    risiko_satz_1: 'Waits for low prices and accepts more risk for it.',
    risiko_satz_2: 'Plans with the median price of the forecast.',
    risiko_satz_3: 'Charges earlier and hedges against rising prices.',
    risiko_alle: 'Applies to all vehicles.',
    ladeplan_bis: 'Charging plan until {tag} {zeit}',
    ladeplan: 'Charging plan',
    strompreis: 'Electricity price',
    termine_aller: 'Trips of all vehicles',
    filter_fahrer: 'Filter by driver',
    filter_alle: 'All',
    filter_ohne: 'No driver',
    keine_termine_tage: 'No trips in the coming days.',

    leg_ladestand: 'State of charge',
    leg_laden: 'Charging',
    leg_unterwegs: 'Away',
    leg_preis: 'Price',
    leg_prognose: 'Forecast',
    diagramm_min: 'Min {soc}',
    diagramm_max: 'Max {soc}',
    diagramm_ziel: 'Target {soc}',
    diagramm_plan: 'Charging plan {name}: state of charge, charging and price over the horizon',
    tip_ladestand: 'State of charge {soc}',
    tip_preis: 'Price {preis}',
    tip_preis_prognose: 'Price {preis} (forecast)',
    tip_laedt: 'Charging {kw}, {eur}',
    tip_unterwegs: 'Away',

    st_unterwegs_bis: 'Away until {zeit}',
    st_laedt_jetzt: 'Charging now, {kw}',
    st_laedt_jetzt_ohne: 'Charging now',
    st_laedt_ab: 'Charging from {zeit}',
    st_kein_laden: 'No charging planned',
    st_warnung_1: '1 trip with a warning',
    st_warnung_n: '{n} trips with a warning',
    morgen_zeit: 'tomorrow {zeit}',

    kz_ladestand: 'State of charge now',
    kz_geplant: 'Planned',
    kz_kosten_mit: 'Cost with grid fees',
    kz_kosten_ohne: 'Cost without grid fees',
    kz_planende: 'At plan end',
    ladebloecke: 'Charging blocks',
    kein_laden_bis_ende: 'No charging planned until the end of the plan.',
    alle_bloecke: 'Show all {n} charging blocks',
    weniger: 'Show less',
    grund_ziel: 'for departure {abfahrt}, target {soc}',
    grund_vor: 'before departure {abfahrt}',
    grund_ende: 'until the end of the plan',
    block_werte: '{kwh} · Ø {preis} · {eur} · {grund}',

    einzeln_geaendert: 'changed individually',
    ziel_soc: 'Target {soc}',
    abfahrt_mit: 'Departure at {soc}',
    ziel_unerreichbar: 'Target {soc} not reachable, {kwh} missing',
    unter_min: 'After the trip {soc}, below the minimum of {min}',
    hinweis_overlap: 'Overlaps another trip of this car',
    hinweis_fahrer: '{fahrer} is on the road with {fahrzeug} at the same time',
    anderes_fahrzeug: 'another vehicle',
    noch_nicht_geplant: 'Not planned yet from {tag} {zeit}',
    keine_termine: 'No trips. Without trips, Meteo-Volt plans without driving.',
    kopf_heute: 'Today, {tag}',
    kopf_morgen: 'Tomorrow, {tag}',
    km: '{km} km',

    regel_once: 'Once',
    regel_daily: 'Daily',
    regel_weekdays: 'Every weekday (Mon–Fri)',
    regel_weekdays_kurz: 'Mon–Fri',
    regel_weekly: 'Weekly on {wochentag}',
    regel_weekly_kurz: 'Every {wochentag}',
    regel_monthly: 'Monthly on the {ordinal} {wochentag}',
    regel_monthly_kurz: 'Monthly',
    regel_yearly: 'Annually on {datum}',

    neuer_termin: 'New trip',
    termin_bearbeiten: 'Edit trip',
    f_abfahrt: 'Departure',
    f_rueckkehr: 'Return',
    f_wiederholung: 'Repeat',
    f_strecke: 'Round-trip distance (km)',
    f_fahrzeug: 'Vehicle',
    f_fahrer: 'Driver',
    f_kein_fahrer: 'No driver',
    f_ladestand: 'State of charge at departure (%)',
    f_sichern: 'Keep minimum SoC',
    f_sichern_hinweis: 'Secures {ziel} % — minimum {min} % plus {fahrt} % for {km} km',
    f_optional: 'optional',

    umfang_aendern: 'Change recurring trip',
    umfang_loeschen: 'Delete recurring trip',
    umfang_this: 'This trip only',
    umfang_following: 'This and all following trips',
    umfang_all: 'All trips',
    umfang_gesperrt: 'Not possible when the repeat changes.',
    umfang_zuruecksetzen: 'Trips of this series that were changed or cancelled individually are reset.',

    ue_titel_1: 'Overlaps one trip',
    ue_titel_n: 'Overlaps {n} trips',
    ue_frage: '{fahrzeug} is already booked for this time. Which trips should be dropped?',
    ue_behalten: 'Keep',
    ue_absagen_1: 'Cancel 1 trip',
    ue_absagen_n: 'Cancel {n} trips',
    ue_einmalig: 'Once',

    m_gespeichert: 'Trip saved. The plan is being recalculated.',
    m_geloescht: 'Trip deleted.',
    m_abgesagt: 'Trip cancelled.',
    m_geloescht_n: 'Trips deleted.',
    m_gespeichert_abgesagt_1: 'Trip saved, 1 trip cancelled.',
    m_gespeichert_abgesagt_n: 'Trip saved, {n} trips cancelled.',

    p_jetzt: 'Price now',
    p_jetzt_mit: 'Price now, with grid fees',
    p_heute: 'Cheapest {h} h today, Ø {preis}',
    p_morgen: 'Cheapest {h} h tomorrow, Ø {preis}',
    p_letzter_tag: 'Last day with exchange prices',
    p_leg_boerse: 'Exchange',
    p_leg_prognose: 'Forecast Q50',
    p_leg_spanne: 'Range Q10 to Q90',
    p_leg_guenstig: 'Cheapest {h} h per day',
    p_prognose_von: 'Forecast from {zeit}, model {modell}.',
    p_je_tag: 'Per day',
    p_laenge: 'Length of the cheapest period',
    p_kopf_tag: 'Day',
    p_kopf_guenstig: 'Cheapest {h} h',
    p_kopf_werte: 'Low, high, mean',
    p_quelle_boerse: 'Exchange',
    p_quelle_prognose: 'Forecast',
    p_ab: 'from {zeit}',
    p_bis: 'until {zeit}',
    p_zu_kurz: 'too short',
    p_werte: 'Low {tief} at {tiefzeit} · High {hoch} at {hochzeit} · Ø {mittel}',
    p_spanne: 'Range ± {spanne}',
    p_keine: 'No forecast yet.',
    p_tip_boerse: 'Exchange price {preis}',
    p_tip_prognose: 'Forecast {preis}',
    p_tip_spanne: 'Range {von} to {bis}',
    p_diagramm: 'Price forecast with range',
    ohne_wert: '–',
    durchschnitt: 'Ø {preis}',
    eur_betrag: '€{betrag}',
    von_bis: '{von}–{bis}',
    soc_von_bis: '{von} → {bis}',
    trenner: ' · ',
  },
};

export const WOERTER = {
  de: {
    wochentage: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
    wochentageKurz: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
    monate: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober',
      'November', 'Dezember'],
    monateKurz: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
    ordinal: ['ersten', 'zweiten', 'dritten', 'vierten', 'letzten'],
  },
  en: {
    wochentage: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    wochentageKurz: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    monate: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October',
      'November', 'December'],
    monateKurz: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    ordinal: ['first', 'second', 'third', 'fourth', 'last'],
  },
};

// 'de-CH' -> 'de'. Alles ausser Deutsch ist Englisch, wie in C3.
export const sprache = (language) => (String(language || '').split('-')[0].toLowerCase() === 'de' ? 'de' : 'en');

// Ein Text mit seinen Platzhaltern. Ein fehlender Platzhalter bleibt als {name} stehen.
export function text(sp, schluessel, platzhalter = {}) {
  const vorlage = TEXTE[sp][schluessel];
  if (vorlage === undefined) throw new Error(`Text fehlt: ${sp}.${schluessel}`);
  return vorlage.replace(/\{(\w+)\}/g, (ganz, name) => (name in platzhalter ? String(platzhalter[name]) : ganz));
}
